Jcsp 417
atlassian/jces-1209 pull request #42
Opened 2020-05-21 12:06 UTC by rsaliiatlassian

2020-05-25 11:01 UTC, dagguh requested changes

2020-05-25 11:01 UTC, dagguh commented on custom-vu/src/main/kotlin/jces1209/vu/page/ClassicCloudCommenting.kt
> +        throw Exception("Not implemented")
With `mentionUserProbability = 1.00f`, this will start throwing errors, so we can't merge it to master.

2020-05-25 11:01 UTC, dagguh commented on custom-vu/src/main/kotlin/jces1209/vu/ScenarioSimilarities.kt
> +            transitionProbability = 1.00f,
Changes unrelated to mentioning should be removed.

2020-05-25 11:01 UTC, dagguh commented on custom-vu/src/main/kotlin/jces1209/vu/page/DcCommenting.kt
> +    override fun mentionUser() {
I had an old branch with mentioning: https://github.com/atlassian/jces-1209/pull/9
I think my old impl used fewer locators and more stable ones.

2020-05-28 10:00 UTC, rsaliiatlassian commented
Close due to squash

2020-05-28 10:00 UTC, closed without merging