JCSP-373: DC, Cloud: JPT test (Edit assignee)
atlassian/jces-1209 pull request #52
Opened 2020-05-28 09:36 UTC by rsaliiatlassian

2020-05-28 10:03 UTC, dagguh requested changes

2020-05-28 10:03 UTC, dagguh commented on custom-vu/src/main/kotlin/jces1209/vu/page/DcIssuePage.kt
> +        var allUsers = driver
`val` is better than `var`

2020-05-28 10:03 UTC, dagguh commented on custom-vu/src/main/kotlin/jces1209/vu/page/DcIssuePage.kt
> +            allUsers[2].text.substringBefore(" - ")
This can throw. `List.get` is indexed from 0.

- [ ] careful when accessing by index

2020-05-29 11:58 UTC, ysemenkov approved these changes

2020-06-01 08:02 UTC, dagguh approved these changes

2020-06-01 08:19 UTC, merged