JCSP-391: DC, Cloud: Quick search top bar
atlassian/jces-1209 pull request #58
Opened 2020-06-05 06:41 UTC by rsaliiatlassian

2020-06-05 15:10 UTC, dagguh submitted a review, later dismissed

2020-06-05 15:10 UTC, dagguh commented on custom-vu/src/main/kotlin/jces1209/vu/ScenarioSimilarities.kt
> +        workOnTopBar = WorkOnTopBar(
Adding it on the end increases risk of Git conflict -> unnecessary work.
Worth keeping in mind for the next time.

2020-06-05 15:10 UTC, dagguh commented on custom-vu/src/main/kotlin/jces1209/vu/page/bars/topBar/AbstractTopBar.kt
> +}
```suggestion
interface TopBar {
    fun quickSearch(): TopBar
}
```

2020-06-09 09:33 UTC, ysemenkov requested changes

2020-06-09 09:33 UTC, ysemenkov commented on custom-vu/src/main/kotlin/jces1209/vu/action/WorkOnTopBar.kt
> +    private val topBar: AbstractTopBar,
It must be compilation error - there is no AbstractTopBar - it's just `TopBar` already

2020-06-09 09:33 UTC, ysemenkov commented on custom-vu/src/main/kotlin/jces1209/vu/action/WorkOnTopBar.kt
> +        meter.measure(ActionType("Quick search top bar") { Unit }) {
Please create it in MeasureType

2020-06-09 09:33 UTC, ysemenkov commented on custom-vu/src/main/kotlin/jces1209/vu/page/bars/topBar/cloud/CloudTopBar.kt
> +            )
ExpectedConditions.and

2020-06-09 09:33 UTC, ysemenkov commented on custom-vu/src/main/kotlin/jces1209/vu/action/WorkOnTopBar.kt
> +        jira.navigateTo("secure/BrowseProjects.jspa")
also, it's necessary to add `wait for page load`

2020-06-09 09:33 UTC, ysemenkov commented on custom-vu/src/main/kotlin/jces1209/vu/page/bars/topBar/dc/DcTopBar.kt
> +        return this
ExpectedConditions.and

2020-06-10 11:23 UTC, ysemenkov submitted a review, later dismissed

2020-06-10 12:14 UTC, ysemenkov approved these changes

2020-06-10 12:14 UTC, merged