JCSP-407: DC, Cloud: View issue types
atlassian/jces-1209 pull request #87
Opened 2020-08-26 05:34 UTC by rsaliiatlassian

2020-08-26 05:44 UTC, NataliiaShavshyna requested changes

2020-08-26 05:44 UTC, NataliiaShavshyna commented on custom-vu/src/main/kotlin/jces1209/vu/page/admin/issuetypes/DcBrowseIssueTypesPage.kt
> +    }
looks like the same as for cloud

2020-08-26 05:56 UTC, ysemenkov commented on custom-vu/src/main/kotlin/jces1209/vu/ScenarioSimilarities.kt
> +            meter = meter,
measure

2020-08-26 06:06 UTC, ysemenkov requested changes

2020-08-26 06:06 UTC, ysemenkov commented on custom-vu/src/main/kotlin/jces1209/vu/page/admin/issuetypes/BrowseIssueTypesPage.kt
> +        ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[. = 'Sub-task']"))
it is too general locators and is related to text
```suggestion
        presenceOfAllElementsLocatedBy(By.cssSelector("[data-issue-type-field]")),
        presenceOfAllElementsLocatedBy(By.cssSelector("[data-type]")),
        presenceOfAllElementsLocatedBy(By.className("operations-list")),
        visibilityOfElementLocated(By.className("search-entry"))
```

2020-08-26 15:04 UTC, ysemenkov requested changes

2020-08-26 15:04 UTC, ysemenkov commented on custom-vu/src/main/kotlin/jces1209/vu/page/admin/issuetypes/CloudBrowseIssueTypesPage.kt
> +            presenceOfElementLocated(By.xpath("//*[@data-testid = 'NavigationItem']")),
```suggestion
            presenceOfAllElementsLocatedBy(By.xpath("//*[@data-testid = 'NavigationItem']")),
```

2020-08-27 05:05 UTC, ysemenkov approved these changes

2020-08-27 10:57 UTC, NataliiaShavshyna approved these changes

2020-08-27 10:59 UTC, merged